# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml ./
COPY README.md ./
COPY uv.lock ./
COPY src ./src

# Upgrade pip and install dependencies including uv
RUN pip install --upgrade pip \
    && pip install hatchling uv \
    && pip install . --no-cache-dir

EXPOSE 8888

CMD ["uv", "run", "spotify-mcp"]
